name: local-kivoll-db

services:
  local-db:
    image: postgres:18
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432"
    healthcheck:
      test: >
        pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
