services:
  worker-base:
    profiles:
      - base
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        GIT_REPO: https://github.com/IgnyteX-Labs/kivoll_worker.git
        GIT_BRANCH: main
    restart: unless-stopped
    env_file:
      - .env.worker

  worker:
    extends:
      service: worker-base
    profiles:
      - prod
    depends_on:
      db:
        condition: service_healthy
    environment:
      KIVOLL_EXTRA_OPTIONS: ""
      DB_NAME: "db"

  worker-local:
    extends:
      service: worker-base
    profiles:
      - local
    depends_on:
      db-local:
        condition: service_healthy
    environment:
      KIVOLL_EXTRA_OPTIONS: "--verbose"
      DB_NAME: "db-local"

  db:
    image: postgres:18
    profiles:
      - prod
    env_file:
      - .env.admin
      - .env.worker
    volumes:
      - pgdata:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-local:
    extends:
      service: db
    profiles:
      - local
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432"

volumes:
  pgdata:
